"""Add client_nom and adresse to User model

Revision ID: 5c4bfbccfb10
Revises: 
Create Date: 2025-03-11 18:16:55.095535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c4bfbccfb10'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fichier_modifie', schema=None) as batch_op:
        # Remove the line that adds the date_livraison column
        # batch_op.add_column(sa.Column('date_livraison', sa.DateTime(), nullable=True))

    with op.batch_alter_table('parametre', schema=None) as batch_op:
        batch_op.alter_column('min_valeur',
                              existing_type=sa.FLOAT(),
                              nullable=True)
        batch_op.alter_column('max_valeur',
                              existing_type=sa.FLOAT(),
                              nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_nom', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('adresse', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('adresse')
        batch_op.drop_column('client_nom')

    with op.batch_alter_table('parametre', schema=None) as batch_op:
        batch_op.alter_column('max_valeur',
                              existing_type=sa.FLOAT(),
                              nullable=False)
        batch_op.alter_column('min_valeur',
                              existing_type=sa.FLOAT(),
                              nullable=False)

    with op.batch_alter_table('fichier_modifie', schema=None) as batch_op:
        # Remove the line that drops the date_livraison column
        # batch_op.drop_column('date_livraison')

    # ### end Alembic commands ###
